# Generated by Django 5.0.7 on 2024-07-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addaitems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField()),
                ('img', models.URLField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'adda_items',
            },
        ),
    ]
