# Generated by Django 5.0.7 on 2024-07-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_addaitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naturalsitems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField()),
                ('img', models.URLField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'naturals_items',
            },
        ),
    ]
