# Generated by Django 5.0.7 on 2024-08-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rasitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usitems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField()),
                ('flag', models.CharField(max_length=1)),
                ('img', models.URLField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'Us_items',
            },
        ),
    ]
