# Generated by Django 5.0.7 on 2024-08-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_usitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='addaitems',
            name='flag',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='addaitems',
            name='stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='naturalsitems',
            name='flag',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='naturalsitems',
            name='stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='rasitems',
            name='stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='usitems',
            name='stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='addaitems',
            name='img',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='naturalsitems',
            name='img',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='rasitems',
            name='img',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='usitems',
            name='img',
            field=models.URLField(max_length=1000),
        ),
    ]
